### PR TITLE
update stylelint rules, add color palettes

### PR DESCRIPTION
**Pull request by thomsebastin**
Please always provide the Jira Issue your PR is for, as well as test URLs where your change can be observed (before and after):

Jira ID: https://jira.corp.adobe.com/browse/EXLM-116

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management
- After: https://feature-exlm-116-color-palette--exlm--adobe-experience-league.hlx.page/docs/integrations-learn/experience-cloud/solution-categories/content-management

### CODE REVIEW

**Comment by thomsebastin** [comment]
Hi @ahmed-musallam,

I wanted to move the newly added variables to a separate file. Turns out the SASS compile code is not considering the `ignore` rules. Was it working for you when you tested in your local? If this is not a blocker for this PR, we can merge this.

Screenshot 2023-10-04 at 11 42 13 AM

**Comment by ahmed-musallam** [comment]
@thomsebastin update this: https://github.com/adobe-experience-league/exlm/blob/main/sass-compile.js#L7
to ignore any files you want to ignore.

Even if the sass compile process compiles the variables file, it's not a blocking issue, just clutter we don't need

**Comment by ahmed-musallam** [comment]
Overall, this looks good to me

**Comment by thomsebastin** [comment]
> @thomsebastin update this: https://github.com/adobe-experience-league/exlm/blob/main/sass-compile.js#L7 to ignore any files you want to ignore.
> 
> Even if the sass compile process compiles the variables file, it's not a blocking issue, just clutter we don't need

I did try in my local, but didn't work for me. I will check again. 

Here's what I did:
Updated `const IGNORED_FILES = [];` to `const IGNORED_FILES = ['sass'];` and created a folder with my SASS variable file there. When I restarted the task it was compiling the `CSS` in `SASS` folder. Anyway, we can handle that separately. I will move this out of draft, so you can approve and merge.

**Pull request merged**
