### PR TITLE
Updated Featured Content block

### PR DESCRIPTION
**Pull request by rrusher**
Updated to pull the author from the Author Summary block.
Updated references to class name 'adobe-ue-preview'.

Jira ID: https://jira.corp.adobe.com/browse/EXLM-1546

Test URLs:

- Before: https://main--exlm--adobe-experience-league.hlx.page/en/featured-content
- After: https://main--exlm--rrusher.hlx.page/en/featured-content

### CODE REVIEW

**Comment by rrusher** [comment]
When I run `npm run format:check` I get "All matched files use Prettier code style". I'm not sure why it is failing here.

**Review by noormd08 — DISMISSED** [review]
Approved and merging for now.
As mentioned earlier, please raise the PR from EXLM Project feature branch to main branch

**Comment by noormd08** [comment]
@gauthamksn / @nitin-rachabathuni Can you please fix the conflicts in this PR and review once. 
CC: @rrusher @Sivaramvt

**Review by gauthamksn — APPROVED** [review]
Resolved conflicts and approved.

**Pull request merged**
